### ISSUE TITLE
Investigate slow response times from endpoints on some devices

### ISSUE THREAD

**Issue by kashifpk** [NebraLtd/hm-diag#248]
Slack discussion: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1637747430275400

TLDR;
-  `/version` endpoint taking somewhere around 1 to 7 minutes to respond.
- `/json` and `/initFile.txt` timing out or returning empty response.

This is only happening with gunicorn running on port 5000. Accessing these endpoints using flask's development server or by running gunicorn on a different port gives results back instantly.

**Comment by kashifpk** [comment]
The connections to hm-diag seem to be in `FIN_WAIT2` state

![image](https://user-images.githubusercontent.com/198638/143373111-ccc0d93e-44d2-4361-903d-1dab00e2f335.png)

> FIN_WAIT_2 seems to occur when the server has an active connection with a client and wants to shut down the TCP connection (probably in response to a normal application layer "exit"). ... From the server's perspective, the connection is now closed, and the server can't send any more data. Since this is on multiple connections that probably takes up all gunicorn threads that are running causing the slow response times.

To check if this was something related to the client not closing the connection properly (unlikely), I tried setting kee-alive to false, and specifying timeouts but that didn't solve the issue.

![image](https://user-images.githubusercontent.com/198638/143373875-9f64fa0f-5bf8-4314-b570-2cc2bf3d101d.png)

**Comment by kashifpk** [comment]
Apparently this is a known issue with docker on linux

I've dome some investigations into stuck connections in FIN-WAIT-2 state for our Nimbus Eth 2.0 Node project which we were running with Docker 20.10.2 on Ubuntu 20.04.1, and the solution that we've chosen was to ditch the docker-proxy by setting userland-proxy:false, which as far as I can tell has fixed the problem with the growing number of FIN-WAIT-2 connections.

https://github.com/docker/for-linux/issues/335

One solution provided was:

> In my opinion the issue is caused by the combination of docker-proxy and a few other circumstances. I say this because we have many other pieces of software using docker-proxy without such stuck connections, so it's not just docker-proxy that triggers this issue.

But need to see if `balena-engine` supports this or not and if this is something we can configure or it's baked into balena images.

This does not happen inside the container itself

```shell
# netstat -pnt | grep FIN_WAIT | wc -l
0
```

There is a more in-depth discussion here:

https://github.com/status-im/infra-nimbus/issues/35

But so far definitely seems like a docker bug.

**Comment by kashifpk** [comment]
So switching to port 7000 does seem to solve this issue. However initFile.txt still gives empty reply.

![image](https://user-images.githubusercontent.com/198638/143378081-b2ae60b5-09a1-4eba-964b-cb6e672e8243.png)

for `/json` and `/version` we get quick replies. `/initFile.txt` takes around 31 seconds and returns an empty reply. This is much faster than before which means that the slow response times issue is fixed and may be this initFile issue is a separate problem.

**Comment by kashifpk** [comment]
Now I can confirm that using port 5000 is causing problems. After using port 7000 and the issue getting resolved, I switched back to using port 5000 and the issue reappeared again.

![image](https://user-images.githubusercontent.com/198638/143383838-a563da7a-9f46-4b1b-9f7c-4ff0b3c8a8be.png)

Since using port 7000 has fixed this for us I think there is no need to investigate it further @vpetersson ?

**Comment by vpetersson** [comment]
> Now I can confirm that using port 5000 is causing problems. After using port 7000 and the issue getting resolved, I switched back to using port 5000 and the issue reappeared again.
> 
> ![image](https://user-images.githubusercontent.com/198638/143383838-a563da7a-9f46-4b1b-9f7c-4ff0b3c8a8be.png)
> 
> Since using port 7000 has fixed this for us I think there is no need to investigate it further @vpetersson ?

I'm still not fully convinced that this is the root cause since we don't understand *why* port 5000 is causing issues.

@robputt do you have any thoughts here?

**Comment by vpetersson** [comment]
@kashifpk can you do a larger set of tests with a large N, say 10?

I'm thinking something like this:

```bash
function {
  time curl http://127.0.0.1:$PORT/version
  sleep $((60 + RANDOM % 120))
}
```

**Comment by kashifpk** [comment]
@vpetersson - yes. You want the tests on the new port 7000? As on 5000 they aren't working any way.

**Comment by vpetersson** [comment]
Yes, i want to run the following experiment on both port 5000 and 7000 with say N=10 to rule out that it isn't just a fluke.

**Comment by shawaj** [comment]
Is this the expected cause of the issues in manufacturing with slow responses?

**Comment by kashifpk** [comment]
@shawaj - not sure yet. @marvinmarnold tried replicating this on a miner but got normal response times. So this could be something that broke specific to the Raspberry Pis we have for testing. Though the issue with `/version` endpoint which only reads a couple of environment variables may suggest that this could occur in manufacturing too. But to confirm that we would need to reproduce this on a miner.

If this is the same issue then it can be detected on miners by analyzing the number of TCP/IP connections on the host that are in FIN_WAIT2 state and on the diagnostics container that are in CLOSE_WAIT state. So we might need more feedback from the miner to analyze this.

I'll try to test against miners on testnet next with random interval between requests as @vpetersson has suggested to see if this issue can be reproduced on the actual hardware.

**Comment by shawaj** [comment]
@kashifpk I'm wondering if this could have something to do with our docker healthchecks and the associated checking for the files:

https://github.com/NebraLtd/hm-diag/blob/c22a42915cb4f029dae41f31076d9867f84894dd/Dockerfile#L35-L48

https://github.com/NebraLtd/hm-config/blob/793f61515fe1f022a5f9e7e5d9ab2c9b24d0da98/start-gateway-config.sh#L3-L8

https://github.com/NebraLtd/hm-miner/blob/655fda50308f2b422bcf9fac527af33cb69205d5/start-miner.sh#L24-L29

I don't see exactly why that would cause issues but thought it was worth mentioning

**Comment by kashifpk** [comment]
@shawaj - If that was the case the responses would be quicker at times when the scheduled health checks were not running. But so far what I've seen is that if the response is slow it remains slow even after hours and repeated attempts. Since this was only happening on the raspberry pi, I de-prioritized it. However a good first step would be to test against testnet or production devices by sending requests to them at random intervals and testing the response times. If we find this issue on the miners then we can make it more urgent to investigate it further.
